# Generated by Django 2.2.3 on 2019-07-18 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_story'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments_changes', models.IntegerField(default=0)),
                ('score_changes', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='services.Story')),
            ],
            options={
                'verbose_name': 'story update',
                'verbose_name_plural': 'stories update',
                'db_table': 'services_story_update',
            },
        ),
    ]
